### ISSUE TITLE
Push to ECR fails

### ISSUE THREAD

**Issue by acquianjperez** [geerlingguy/ansible-role-ecr_container_build#7]
Pushing an image to ECR fails with the following:

TASK [geerlingguy.ecr_container_build : Push image to ECR.] ********************
FAILED - RETRYING: Push image to ECR. (10 retries left).
FAILED - RETRYING: Push image to ECR. (9 retries left).
FAILED - RETRYING: Push image to ECR. (8 retries left).
FAILED - RETRYING: Push image to ECR. (7 retries left).
FAILED - RETRYING: Push image to ECR. (6 retries left).
FAILED - RETRYING: Push image to ECR. (5 retries left).
FAILED - RETRYING: Push image to ECR. (4 retries left).
FAILED - RETRYING: Push image to ECR. (3 retries left).
FAILED - RETRYING: Push image to ECR. (2 retries left).
FAILED - RETRYING: Push image to ECR. (1 retries left).
fatal: [127.0.0.1]: FAILED! => {"attempts": 10, "changed": false, "msg": "Error pulling image <REDACTED> - 404 Client Error: Not Found (\"pull access denied for <REDACTED>, repository does not exist or may require 'docker login'\")"}

**Comment by geerlingguy** [comment]
I discussed this with @acquianjperez outside of GitHub, but basically, with the way Ansible's `docker_image` works, there are some strange behaviors if you want to use the module to just 'push a docker image to a registry'.

In my case, I want to definitively run a `docker push` command, in every circumstance, and `docker_image` was not doing that for me, unfortunately. And if I set `force: yes` (like in #6), then it would try `pull`ing the image, which was hitting a 404 since the image wasn't yet in the registry (because I wanted to push it!).

Anyways, the approach in #8 should be more reliable, because I definitely want to push the container image in every circumstance... even if it already exists, I want to run a `docker push` on it.
